project_id = "vzskdskwikmnrgngiyib"

[functions.deconstruct]
verify_jwt = false

[functions.simulate]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.narrative]
verify_jwt = false