// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vzskdskwikmnrgngiyib.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6c2tkc2t3aWttbnJnbmdpeWliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwODY0NDQsImV4cCI6MjA3MzY2MjQ0NH0.kapu7YiEOdwvx9UzZGzAhg8yPQGqS77GXtSqJSKYCUw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});